
export const data = [
    {
      "id": 1,
      "name": "Wireless Noise-Cancelling Headphones",
      "description": "Premium headphones with active noise-cancellation.",
      "price": 249.99,
      "image": "https://fakeimg.pl/500x500/ff6600",
      "rating": 4.5,
      "brand": "Sony",
      "color": "Black",
      "connectivity": "Bluetooth",
      "wireless": true
    },
    {
      "id": 2,
      "name": "Smartphone Camera Gimbal",
      "description": "Stabilize your smartphone videos with this advanced gimbal.",
      "price": 159.99,
      "image": "https://fakeimg.pl/500x500/33aa33",
      "rating": 4.2,
      "brand": "DJI",
      "compatibility": "iOS, Android",
      "weight": "250g"
    },
    {
      "id": 3,
      "name": "Professional DSLR Camera",
      "description": "Capture stunning photos with this high-end DSLR camera.",
      "price": 1899.99,
      "image": "https://fakeimg.pl/500x500/4466cc",
      "rating": 4.8,
      "brand": "Canon",
      "resolution": "24.2MP",
      "sensor": "Full-frame"
    },
    {
      "id": 4,
      "name": "Ultrabook Laptop",
      "description": "Slim and lightweight laptop for productivity on the go.",
      "price": 999.99,
      "image": "https://fakeimg.pl/500x500/990099",
      "rating": 4.6,
      "brand": "Lenovo",
      "screen_size": "14 inches",
      "storage": "512GB SSD",
      "ram": "16GB"
    },
    {
      "id": 5,
      "name": "Fitness Tracker Watch",
      "description": "Monitor your health and activity with this smartwatch.",
      "price": 89.99,
      "image": "https://fakeimg.pl/500x500/0099cc",
      "rating": 4,
      "brand": "Fitbit",
      "display": "Color touchscreen",
      "heart_rate_monitor": true,
      "waterproof": true
    },
    {
      "id": 6,
      "name": "Gaming Console",
      "description": "Immerse yourself in gaming with the latest console.",
      "price": 399.99,
      "image": "https://fakeimg.pl/500x500/ff3399",
      "rating": 4.9,
      "brand": "Sony",
      "storage": "1TB",
      "resolution": "4K",
      "games_included": 2
    },
    {
      "id": 7,
      "name": "Wireless Charging Pad",
      "description": "Charge your devices wirelessly with this sleek charging pad.",
      "price": 39.99,
      "image": "https://fakeimg.pl/500x500/ffcc00",
      "rating": 4.3,
      "brand": "Anker",
      "compatibility": "Qi-enabled devices",
      "output_power": "10W",
      "color": "White"
    },
    {
      "id": 8,
      "name": "Robot Vacuum Cleaner",
      "description": "Keep your floors clean with this smart robot vacuum.",
      "price": 299.99,
      "image": "https://fakeimg.pl/500x500/66cc66",
      "rating": 4.7,
      "brand": "iRobot",
      "suction_power": "2000Pa",
      "battery_life": "90 minutes",
      "mapping_technology": true
    },
    {
      "id": 9,
      "name": "Bluetooth Speaker",
      "description": "Portable speaker with powerful sound and long battery life.",
      "price": 79.99,
      "image": "https://fakeimg.pl/500x500/ff9933",
      "rating": 4.5,
      "brand": "JBL",
      "output_power": "20W",
      "battery_life": "12 hours",
      "waterproof": true
    },
    {
      "id": 10,
      "name": "Portable External SSD",
      "description": "Fast and compact external SSD for data storage and transfer.",
      "price": 149.99,
      "image": "https://fakeimg.pl/500x500/3399ff",
      "rating": 4.8,
      "brand": "Samsung",
      "storage_capacity": "500GB",
      "interface": "USB 3.2 Gen 2",
      "color": "Blue"
    },
    {
      "id": 11,
      "name": "Electric Scooter",
      "description": "Eco-friendly electric scooter for urban commuting.",
      "price": 349.99,
      "image": "https://fakeimg.pl/500x500/ff6666",
      "rating": 4.6,
      "brand": "Xiaomi",
      "max_speed": "25 km/h",
      "range": "20 km",
      "weight_capacity": "100 kg"
    },
    {
      "id": 12,
      "name": "Kitchen Blender",
      "description": "Powerful blender for smoothies, soups, and more.",
      "price": 89.99,
      "image": "https://fakeimg.pl/500x500/33cc99",
      "rating": 4.4,
      "brand": "Vitamix",
      "power": "1200W",
      "speeds": "Variable speed control",
      "color": "Green"
    },
    {
      "id": 13,
      "name": "Wireless Gaming Mouse",
      "description": "Precision gaming mouse with customizable RGB lighting.",
      "price": 59.99,
      "image": "https://fakeimg.pl/500x500/993366",
      "rating": 4.7,
      "brand": "Logitech",
      "dpi_range": "100 - 16000",
      "wireless": true,
      "buttons": 6
    },
    {
      "id": 14,
      "name": "Fitness Treadmill",
      "description": "High-performance treadmill for home workouts.",
      "price": 899.99,
      "image": "https://fakeimg.pl/500x500/66cccc",
      "rating": 4.5,
      "brand": "ProForm",
      "max_speed": "18 km/h",
      "incline_levels": 15,
      "display": "Touchscreen",
      "foldable": true
    },
    {
      "id": 15,
      "name": "Smart Thermostat",
      "description": "Programmable thermostat for energy-efficient temperature control.",
      "price": 129.99,
      "image": "https://fakeimg.pl/500x500/cc9966",
      "rating": 4.3,
      "brand": "Nest",
      "compatibility": "iOS, Android",
      "connectivity": "Wi-Fi",
      "voice_control": true
    },
    {
      "id": 16,
      "name": "Portable Solar Charger",
      "description": "Charge your devices using solar power on the go.",
      "price": 49.99,
      "image": "https://fakeimg.pl/500x500/ff9900",
      "rating": 4.2,
      "brand": "Goal Zero",
      "capacity": "10000mAh",
      "solar_panel_power": "7W",
      "waterproof": true
    },
    {
      "id": 17,
      "name": "Yoga Mat",
      "description": "High-quality yoga mat for comfortable workouts.",
      "price": 29.99,
      "image": "https://fakeimg.pl/500x500/99cc99",
      "rating": 4.6,
      "brand": "Liforme",
      "material": "Eco-friendly TPE",
      "thickness": "5mm",
      "color": "Purple"
    },
    {
      "id": 18,
      "name": "Portable Bluetooth Projector",
      "description": "Project your favorite content anywhere with this compact projector.",
      "price": 179.99,
      "image": "https://fakeimg.pl/500x500/ff66cc",
      "rating": 4.3,
      "brand": "Anker",
      "resolution": "720p",
      "connectivity": "Bluetooth, Wi-Fi",
      "battery_life": "3 hours"
    },
    {
      "id": 19,
      "name": "Electric Toothbrush",
      "description": "Advanced electric toothbrush for effective oral care.",
      "price": 69.99,
      "image": "https://fakeimg.pl/500x500/009966",
      "rating": 4.5,
      "brand": "Oral-B",
      "brushing_modes": [
        "Clean",
        "Whitening",
        "Sensitive"
      ],
      "timer": true,
      "color": "Blue"
    },
    {
      "id": 20,
      "name": "Indoor Plant Set",
      "description": "Assortment of low-maintenance indoor plants.",
      "price": 39.99,
      "image": "https://fakeimg.pl/500x500/99cc00",
      "rating": 4.8,
      "brand": "Greenspaces",
      "plants_included": [
        "Snake Plant",
        "Pothos",
        "Succulent"
      ],
      "pot_material": "Ceramic",
      "pot_color": "Assorted"
    },
    {
      "id": 21,
      "name": "Smart Doorbell Camera",
      "description": "Monitor your doorstep with this video doorbell.",
      "price": 149.99,
      "image": "https://fakeimg.pl/500x500/ff9966",
      "rating": 4.7,
      "brand": "Ring",
      "video_resolution": "1080p",
      "field_of_view": "160 degrees",
      "connectivity": "Wi-Fi"
    },
    {
      "id": 22,
      "name": "Electric Standing Desk",
      "description": "Adjustable standing desk for ergonomic workspace setup.",
      "price": 349.99,
      "image": "https://fakeimg.pl/500x500/336699",
      "rating": 4.6,
      "brand": "Vari",
      "adjustable_height": true,
      "max_height": "50 inches",
      "color": "Black"
    }]